### ISSUE TITLE
No Issue (Tibia Counters)

### ISSUE THREAD

**Issue by ahmedwaked90** [Galarzaa90/tibiawiki-sql#14]
Hello Galarzaa,

am using your project to make a project [Tibia Counters] as per below link you could check it, the only issue am facing is with imbuements and db:
DB:  i can't debug this db from python so am always waiting you
Imbuements: i think that you can retrieve full data from wiki, i already made it (not full) but its take much time, so please consider this in your next release.
thx

links:
http://prntscr.com/k1yvwa
http://prntscr.com/k1yw15
http://prntscr.com/k1yw5x
http://prntscr.com/k1yw9w
http://prntscr.com/k1ywyz
http://prntscr.com/k1yxag

**Comment by ahmedwaked90** [comment]
oh my god i didn't check last update yet but its shown new tables sorry for distrub

**Comment by Galarzaa90** [comment]
Yes, I added this on 1.0.0 :+1: 

I guess I can close this issue.
