### ISSUE TITLE
Improve database init code

### ISSUE THREAD

**Issue by Tschis** [Galarzaa90/tibiawiki-sql#19]
- [x] Extract all table creation SQL into new methods for better readability and maintainability;
- [x] Reuse connection from 'main' instead of opening new one;

**Comment by Galarzaa90** [comment]
It should be considered that there's a `feat-rewrite` is pending, so maybe these changes should be incorporated there to avoid duplicates.

**Comment by Tschis** [comment]
Closing after relase.
