### ISSUE TITLE
Migrate to tibia.fandom.com

### ISSUE THREAD

**Issue by Tschis** [Galarzaa90/tibiawiki-sql#23]
Due to wiki domain being migrated to fandom.com. 
More info in [this FANDOM news blog](http://community.wikia.com/wiki/User_blog:Brandon_Rhea/How_we%27re_testing_the_fandom.com_domain_migration).

**Comment by Galarzaa90** [comment]
Yes, in the rewrite I already changed it, and the old domain still work as far as I know.
I expect to finish it soon, if not, I will do a hotfix.

**Comment by Tschis** [comment]
No rush, just a reminder. I didn't check the branches.
They plan on migrating in 2019, so I think you have plenty of time.
