### ISSUE TITLE
No longer fetches items

### ISSUE THREAD

**Issue by thwestlund** [Galarzaa90/tibiawiki-sql#42]
The articles are no longer under Category:Items, but instead Category:Objects. The database will generate 0 items.

Change naming of the Class and category parameters from Item to Object seems to be enough to solve it.

There are a few other items that are not being fetched properly:

> Could not parse 28 articles.
        -> Bone Key,Bronze Prison Key,Chayenne's Magical Key,Copper Key,Copper Prison Key,Crystal Key,TibiaWiki:Featured Item/Week 11, 2010,Forged Glowing Key,Forged Key,Goblin Bone Key,Golden Key,Golden Prison Key,Green Key,Key 3600,Key of Numerous Locks,Key of Numerous Locks (Replica),Magical Cage Key,Magical Key,Old Silver Key,Prison Cell Key,Silver Key,Silver Key (Outpost),Silver Prison Key,User:Slug the third/Keys,User:Slug the third/sandbox,Theodore Loveless' Key,Tin Key,Wooden Key]

among a few other minor ones.

**Comment by Galarzaa90** [comment]
This is already working on in the dev branch. There's also a prerelease for this:

PyPi: https://pypi.org/project/tibiawikisql/6.0.0a2/
GitHub: https://github.com/Galarzaa90/tibiawiki-sql/releases/tag/v6.0.0a2

A proper release will come soon™️
