### ISSUE TITLE
Idea: Run CI weekly to ensure parsers are still working on TibiaWiki pages

### ISSUE THREAD

**Issue by antedeguemon** [Galarzaa90/tibiawiki-sql#44]
Coming from #43, I think it is a good idea to run a CI action weekly to ensure parsers are still working. Seems the project had stopped working for some time until @gooshtavow and @Heckfer noticed.

I'm not sure if this snippet would work, but [here is a blogpost](https://www.jeffgeerling.com/blog/2020/running-github-actions-workflow-on-schedule-and-other-events) on scheduling a Github Action.

**Comment by Galarzaa90** [comment]
Made database github action to also run weekly.
