### ISSUE TITLE
date in unexpected format in one of the latest "updates" articles

### ISSUE THREAD

**Issue by coffeeinmypaintwater** [Galarzaa90/tibiawiki-sql#45]
Parsing updates █████████░ 570/577  00:00:00  Updates/13.36.5b5f56   
Traceback (most recent call last):
  File "/home/user/miniconda/envs/tibia/lib/python3.11/site-packages/tibiawikisql/utils.py", line 204, in parse_date
    dt = datetime.datetime.strptime(value, "%B %d, %Y")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/envs/tibia/lib/python3.11/_strptime.py", line 567, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda/envs/tibia/lib/python3.11/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains:  17:45

  File "/home/victor/miniconda/envs/tibia/lib/python3.11/_strptime.py", line 567, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victor/miniconda/envs/tibia/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'May 14, 2024 17:45' does not match format '%Y'

**Comment by coffeeinmypaintwater** [comment]
I added possible date formats to the utils.py/parse_date as follows to get around the issue.

def parse_date(value):
    """Parse a date from the formats used in TibiaWiki.

    - June 28, 2019
    - Aug 21, 2014
    - May 14, 2024 17:45

    Parameters
    ----------
    value: :class:`str`
        The string containing the date.

    Returns
    -------
    :class:`str`
        The date represented by the string in ISO format.
    """
    value = value.strip()
    date_formats = [
        "%B %d, %Y %H:%M",
        "%B %d, %Y",
        "%b %d, %Y %H:%M",
        "%b %d, %Y",
        "%Y %H:%M",
        "%Y"
    ]

    for date_format in date_formats:
        try:
            dt = datetime.datetime.strptime(value, date_format)
            return dt.date().isoformat()
        except ValueError:
            continue

    raise ValueError(f"Date format for value '{value}' not recognized")

**Comment by Galarzaa90** [comment]
Thank you! This is fixed in the v6.2.1
