### ISSUE TITLE
Study the feasibility/usefulness of adding creatures classification/type

### ISSUE THREAD

**Issue by Tschis** [Galarzaa90/tibiawiki-sql#6]
Evaluate the feasibility/usefulness of adding creatures classification/type (e.g., [Lycanthropes](http://tibia.wikia.com/wiki/Lycanthropes) or [Demons](http://tibia.wikia.com/wiki/Demons)).

**Comment by Galarzaa90** [comment]
Adding this would be trivial, the potential extra size is negligible, so I don't see why this shouldn't be added.

On the other hand, with the introduction of the Winter Update, CipSoft will have monster categories, and they will probably be different than the ones that wiki uses.

We don't know if they would update theirs, or add an extra field specifically for CipSoft's category. Maybe it would be convenient to wait to see how that evolves.

**Comment by Galarzaa90** [comment]
Creature class and type were added in commit 1d20ee6335c2261a31a91f934b2ba186cfd86527
