### ISSUE TITLE
Verify model of table 'npcs' for columns 'name' and 'title'

### ISSUE THREAD

**Issue by Tschis** [Galarzaa90/tibiawiki-sql#8]
### Verify model of table **npcs** for columns **name** and **title**.

Currently, the **title** column is basically the real representation of a NPC's name.
915 out of 940 NPCs have null content for **name**, while none has null **title**.

This is a bit misleading if you're just using the database directly, and the Query API would have calls like "fetch_npc_by_name" and then filter by **title**, which would be anti-intuitive.

I guess there has to be a decision of what the entities in the model are going to be based in:
- Follow strictly the JSON structure from wikia's API;
  - Query API would have to deal with it, which isn't a big problem, it would be transparent for the API and its users;
  - It could cause confusion for the database users in the long run;
- Create an entity based on what would be the best structure;
  - Would make API more intuitive;
  - Would be best for database users in the long run;
  - Might be worse to maintain the parsing code;

**Comment by Galarzaa90** [comment]
Which database file are you checking? Cause in my database, they all have `name` and `title` filled.

Title is only mean to be the article's exact title, while "name" the actual name of the NPC in game. The same goes for the other models.

**Comment by Tschis** [comment]
From release [v0.1.0](https://github.com/Galarzaa90/tibiawiki-sql/releases/download/v0.1.0/tibia_database.db):
  `select count(*) from npcs where name is null`
  `returns 915`

**Comment by Galarzaa90** [comment]
Guess it went away with the changes I made to the parsing code. I will push another release. Thanks!
